//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11_12lab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            // Устанавливаем дату по умолчанию в конструкторе
            CreatedDate = DateTime.Now;
        }

        public int Id { get; set; }
        public string Number { get; set; }
        public int Year { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Condition { get; set; }
        public string OwnerName { get; set; }
        public string Address { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
